# Generated by Django 5.2.1 on 2025-06-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProName',
            new_name='name',
        ),
    ]
