# Generated by Django 5.2.1 on 2025-06-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment_cart_delete_paymentproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
    ]
