# Generated by Django 5.2.1 on 2025-06-26 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_payment_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardType',
            field=models.CharField(choices=[('visa', 'Visa'), ('paypal', 'PayPal'), ('rupay', 'RuPay'), ('mastercard', 'MasterCard')], max_length=10, verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cart'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
