# Generated by Django 5.2.1 on 2025-06-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_payment_cardtype_alter_payment_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ExpirationDate',
            new_name='expirationDate',
        ),
    ]
