# Generated by Django 5.2.1 on 2025-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_expirationdate_payment_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('pinding', 'pinding')], max_length=10, null=True),
        ),
    ]
