# Generated by Django 5.2.3 on 2025-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cart_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('pinding', 'pinding')], default='pinding', max_length=10, null=True),
        ),
    ]
